### ISSUE TITLE
Dialogue chathead

### ISSUE THREAD

**Issue by Nikskill** [claudiodekker/runelite-nievive#1]
The chathead when talking to Nieve still shows Steve, both when talking to her normally and using NPC contact.

![RuneLite_3XBb71kkW1](https://user-images.githubusercontent.com/60371751/233753959-2b0bf7b0-7f39-433c-a068-e345eaa05e27.png)

**Comment by claudiodekker** [comment]
Yeah, sometimes this happens when switching on/off the plugin, or when switching it on after having already had an interaction with the NPC in-game during that "session". It has to do with some internal variables I couldn't find/modify.

If you re-start Runelite (so that the game hasn't had a chance to "set" those variables yet) and have the plugin on before interacting with Nieve, this shouldn't occur.

I'll close this issue now, but if this didn't solve your issue, feel free to leave a comment on this issue detailing the steps you took to have this occur, so that I can attempt to re-create it and re-open this issue!
